// Code generated by options-gen. DO NOT EDIT.
package schemes

import (
	"encoding/xml"
)

type OptEvtInfoEmpregadorSetter func(o *EvtInfoEmpregador)

func NewEvtInfoEmpregador(
	options ...OptEvtInfoEmpregadorSetter,
) EvtInfoEmpregador {
	o := EvtInfoEmpregador{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithInfoEmpXMLName(opt xml.Name) OptEvtInfoEmpregadorSetter {
	return func(o *EvtInfoEmpregador) {
		o.XMLName = opt

	}
}

func WithInfoEmpIdAttr(opt string) OptEvtInfoEmpregadorSetter {
	return func(o *EvtInfoEmpregador) {
		o.IdAttr = opt

	}
}

func WithInfoEmpIdeEvento(opt string) OptEvtInfoEmpregadorSetter {
	return func(o *EvtInfoEmpregador) {
		o.IdeEvento = opt

	}
}

func WithInfoEmpIdeEmpregador(opt *IdeEmpregador) OptEvtInfoEmpregadorSetter {
	return func(o *EvtInfoEmpregador) {
		o.IdeEmpregador = opt

	}
}

func WithInfoEmpInfoEmpregador(opt *InfoEmpregador) OptEvtInfoEmpregadorSetter {
	return func(o *EvtInfoEmpregador) {
		o.InfoEmpregador = opt

	}
}

func (o *EvtInfoEmpregador) Validate() error {
	return nil
}
